import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Jenilson Francisco",
  description: "Generated by create next app",
  openGraph: {
    title: "Jenilson Francisco Dev",
    description: "Quer digitalizar o seu negócio entre em contacto comigo e vamos trabalhar juntos",
    images: ['https://github.com/jenilson25francisco.png']
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${ubuntu.className} dark antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
